// <auto-generated />
using System;
using CarSharingWebsite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarSharingWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260322220317_AddCarLicensePlate")]
    partial class AddCarLicensePlate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarSharingWebsite.Models.Administrator", b =>
                {
                    b.Property<int>("ID_User")
                        .HasColumnType("int");

                    b.Property<bool?>("_view_statistics")
                        .HasColumnType("bit");

                    b.Property<bool?>("control_rentals")
                        .HasColumnType("bit");

                    b.Property<bool?>("manage_cars")
                        .HasColumnType("bit");

                    b.Property<bool?>("manage_tariffs")
                        .HasColumnType("bit");

                    b.HasKey("ID_User");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Booking", b =>
                {
                    b.Property<int>("ID_Booking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Booking"));

                    b.Property<int>("ID_Car")
                        .HasColumnType("int");

                    b.Property<int>("ID_User")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("end_datetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("start_datetime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Booking");

                    b.HasIndex("ID_Car");

                    b.HasIndex("ID_User");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Car", b =>
                {
                    b.Property<int>("ID_Car")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Car"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Brand")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ID_User")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.Property<string>("condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("plate_number")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID_Car");

                    b.HasIndex("ID_User");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Client", b =>
                {
                    b.Property<int>("ID_User")
                        .HasColumnType("int");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("money");

                    b.Property<string>("license_number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_User");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Location", b =>
                {
                    b.Property<int>("ID_Map")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Map"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Map_point")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Map");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Payment", b =>
                {
                    b.Property<int>("ID_payment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_payment"));

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("amount")
                        .HasColumnType("money");

                    b.Property<DateTime?>("payment_datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("payment_method")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID_payment");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Rental", b =>
                {
                    b.Property<int>("ID_Rental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Rental"));

                    b.Property<int>("ID_Car")
                        .HasColumnType("int");

                    b.Property<int>("ID_Tariff")
                        .HasColumnType("int");

                    b.Property<int>("ID_User")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("start_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("total_cost")
                        .HasColumnType("money");

                    b.HasKey("ID_Rental");

                    b.HasIndex("ID_Car");

                    b.HasIndex("ID_Tariff");

                    b.HasIndex("ID_User");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Review", b =>
                {
                    b.Property<int>("ID_review")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_review"));

                    b.Property<int>("ID_User")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("review_date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_review");

                    b.HasIndex("ID_User");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Tariff", b =>
                {
                    b.Property<int>("ID_Tariff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Tariff"));

                    b.Property<int>("ID_Car")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("min_duration")
                        .HasColumnType("int");

                    b.Property<decimal?>("price_per_hour")
                        .HasColumnType("money");

                    b.Property<decimal?>("price_per_minute")
                        .HasColumnType("money");

                    b.HasKey("ID_Tariff");

                    b.HasIndex("ID_Car");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.User", b =>
                {
                    b.Property<int>("ID_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_User"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("first_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("last_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("middle_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("password")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("registration_date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Administrator", b =>
                {
                    b.HasOne("CarSharingWebsite.Models.User", "User")
                        .WithOne("Administrator")
                        .HasForeignKey("CarSharingWebsite.Models.Administrator", "ID_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Booking", b =>
                {
                    b.HasOne("CarSharingWebsite.Models.Car", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("ID_Car")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSharingWebsite.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Car", b =>
                {
                    b.HasOne("CarSharingWebsite.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Client", b =>
                {
                    b.HasOne("CarSharingWebsite.Models.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("CarSharingWebsite.Models.Client", "ID_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Rental", b =>
                {
                    b.HasOne("CarSharingWebsite.Models.Car", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("ID_Car")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSharingWebsite.Models.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("ID_Tariff")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSharingWebsite.Models.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Tariff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Review", b =>
                {
                    b.HasOne("CarSharingWebsite.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Tariff", b =>
                {
                    b.HasOne("CarSharingWebsite.Models.Car", "Car")
                        .WithMany("Tariffs")
                        .HasForeignKey("ID_Car")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.Car", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Rentals");

                    b.Navigation("Tariffs");
                });

            modelBuilder.Entity("CarSharingWebsite.Models.User", b =>
                {
                    b.Navigation("Administrator");

                    b.Navigation("Bookings");

                    b.Navigation("Client");

                    b.Navigation("Rentals");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
